---
title: "Deel 4"
description: |
  A short description of the post.
author: []
date: 01-09-2021
output:
  distill::distill_article:
    self_contained: false
draft: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.



```{r}
klim %>%
  drop_na(Outdoor_RP_boulder, Indoor_RP_boulder) %>%
  ggplot(aes(x = Indoor_RP_boulder, y = Outdoor_RP_boulder)) +
  geom_hline(yintercept = c("5a", "6a", "7a", "8a"), linetype = "dashed", color = "#444444") +
  geom_hline(yintercept = c("6b+", "7b+"), linetype = "dashed", color = "#dddddd") +
  geom_rect(xmin = 0.5, xmax=1.5, ymin = -Inf, ymax = 2.5, alpha = 0.005, fill = green) + 
  geom_rect(xmin = 1.5, xmax=2.5, ymin = -Inf, ymax = 5.5, alpha = 0.005, fill = orange) +
  geom_rect(xmin = 2.5, xmax=3.5, ymin = -Inf, ymax = 9.5, alpha = 0.005, fill = blue) + 
  geom_rect(xmin = 3.5, xmax=4.5, ymin = 1.5, ymax = 12.5, alpha = 0.005, fill = red) +
  geom_rect(xmin = 4.5, xmax=5.5, ymin = 1.5, ymax = 15.5, alpha = 0.005, fill = black) +
  geom_rect(xmin = 5.5, xmax=6.5, ymin = 11.5, ymax = 16.5, alpha = 0.005, fill = white) +
  geom_rect(xmin = 6.5, xmax=7.5, ymin = 12.5, ymax = +Inf, alpha = 0.005, fill = insane) +
  geom_count(show.legend = F) 
  
```